export const CONTENT_DEFAULTS: Record<string, Record<string, string>> = {
  hero: {
    badge: 'Cornell Lab of Ornithology · Rose Postdoctoral Fellow',
    headline: 'Listening to the',
    headline_accent: 'urban ecosystem.',
    tagline: 'Advancing conservation through bioacoustics and urban ecology. Studying how urbanization shapes bird communities and the relationship between people and nature.',
    btn_primary: 'Explore Research',
    btn_secondary: 'Get in Touch',
    institution: 'K. Lisa Yang Center for Conservation Bioacoustics, Cornell Lab of Ornithology',
  },
  about: {
    tagline: 'My research spans landscape and urban ecology, with broad interests in plant–animal interactions and the ecological and social impacts of urbanization and land-use change on bird communities in relation to human well-being.',
    para1: 'My trajectory from Nigeria to South Africa, to Canada, and now to the Cornell Lab of Ornithology has been shaped by a deep curiosity about how species adapt—or fail to adapt—to rapid environmental change. I use an interdisciplinary approach that integrates bioacoustics and community engagement to monitor biodiversity in rapidly changing urban landscapes.',
    para2: 'As a Rose Postdoctoral Fellow at the K. Lisa Yang Center for Conservation Bioacoustics at the Cornell Lab of Ornithology, my current research investigates bird diversity on university campuses and in cities across multiple countries using autonomous acoustic recorders. I collaborate with local experts and students to record bird songs, identifying which species persist, which do not, and why—helping us understand the factors that shape urban bird populations and guiding conservation planning.',
    para3: 'I aim to develop conservation frameworks that support both ecological resilience and social well-being in urban settings. Before joining Cornell, I was a Postdoctoral Research Fellow in the Department of Biology at Queen\'s University in Canada, where I led a global urban bird survey project spanning five countries — Brazil, Canada, France, Kenya, and Senegal — using passive acoustic recorders and an innovative Community Science approach that actively involved local experts and the public in data collection. My doctoral research at the University of KwaZulu-Natal in South Africa focused on frugivory and seed dispersal by birds, bats, and monkeys in urban mosaic landscapes, with particular attention to the ecological role of Ficus species.',
    para4: 'I enjoy working with students and community and local scientists to co-design participatory monitoring methods that are scalable, community-driven, and relevant to both science and society. I am passionate about mentorship, outreach, and interdisciplinary collaboration.',
  },
  research: {
    bg_image: '',
    intro: 'My research program asks fundamental questions about ecological resilience in the Anthropocene. I focus on understanding how we can build cities that act as refuges rather than barriers to biodiversity.',
    theme1_title: 'Bioacoustics',
    theme1_desc: 'Using sound as a non-invasive lens to monitor biodiversity, revealing hidden ecological patterns in urban environments.',
    theme2_title: 'Urban Ecology',
    theme2_desc: 'Investigating how rapid urbanization shapes bird communities and alters fundamental plant-animal interactions.',
    theme3_title: 'Human-Nature Dynamics',
    theme3_desc: 'Exploring the relationship between people and nature, emphasizing community engagement for sustainable cities.',
  },
  mentorship: {
    intro: 'Science is deeply collaborative. My mentorship philosophy is rooted in creating inclusive spaces where diverse voices can shape ecological research.',
    para2: 'I actively seek to support emerging scholars, particularly from underrepresented backgrounds in ecology. Whether through formal supervision, field training, or collaborative analysis, I believe in empowering the next generation of conservation scientists to lead with rigor and empathy.',
    quote: 'Ecology needs diverse perspectives to solve complex environmental challenges. The best science happens when everyone has a seat at the table.',
    application: 'Please reach out if you are interested in urban bioacoustics, plant-animal interactions, or community science. I welcome prospective graduate students, postdocs, and collaborators. Send me an email at iar32@cornell.edu with a brief description of your interests.',
  },
  outreach: {
    email: 'iar32@cornell.edu',
    institution: 'K. Lisa Yang Center for Conservation Bioacoustics, Cornell Lab of Ornithology',
    location: 'Ithaca, NY, USA',
    intro: 'Whether you\'re a prospective student, a potential collaborator, or just interested in urban ecology and bioacoustics, I\'d love to hear from you.',
    community_text: 'I am committed to making science accessible and relevant to communities. I regularly engage with citizen science initiatives, school programs, and public lectures.',
    linkedin: 'https://www.linkedin.com/in/islamiat-raji-adebayo-ph-d-21931387/',
    researchgate: '',
    google_scholar: '',
  },
  teaching: {
    bg_image: '',
    intro: '',
  },
  opportunities: {
    intro: 'I am always looking for motivated and curious students and collaborators to join my research group. I am particularly interested in working with people who are passionate about urban ecology, bioacoustics, and conservation biology.',
    contact_cta: 'To express interest, please email iar32@cornell.edu with your CV, a brief statement of research interests, and any relevant experience.',
  },
  outreach_page: {
    bg_image: '',
    intro: 'Sharing science with broader audiences is central to my work. Through public engagement and writing, I aim to make ecology and conservation accessible, relevant, and inspiring to communities beyond academia.',
    subintro: 'From classroom visits and community workshops to popular articles and podcasts, I enjoy translating research into stories that connect people with the natural world around them.',
    engagement_text: 'A selection of talks, workshops, citizen-science initiatives, and community events I have led or contributed to.',
    writing_text: 'Selected popular articles, blog posts, and op-eds written for general audiences.',
  },
  field_work_page: {
    bg_image: '',
    intro: 'My research is deeply grounded in fieldwork — in the quiet patience of listening to forest edges at dawn, in the careful documentation of birds foraging on fruiting trees, and in the collaborative effort of training communities to listen and record alongside me.',
  },
  resources_section: {
    title: 'Resources',
    intro: 'A curated list of scholarships, internships, fellowships, research grants and recruitment opportunities for undergraduates, graduate students, postdoctoral researchers, and collaborators in ecology, bioacoustics, and conservation science. Filter by audience to find what is most relevant to you.',
  },
};

export const LIST_DEFAULTS: Record<string, Array<Record<string, any>>> = {
  education: [
    { degree: 'PhD Ecological Sciences', institution: 'University of KwaZulu-Natal, 2021' },
    { degree: 'MSc Conservation Biology', institution: 'A.P. Leventis Ornithological Research Institute / University of Jos, 2018' },
    { degree: 'BSc Forestry and Wildlife Management', institution: 'University of Ilorin, 2015' },
  ],
  awards: [
    { title: 'Falling Walls Female Science Talent', year: '2024' },
    { title: 'National Postdoctoral Association IMPACT Fellow', year: '2024' },
    { title: 'NRF-TWAS Scholar', year: '' },
  ],
  nav_items: [
    { name: 'Home', href: '/', accent: false },
    { name: 'About', href: '/about', accent: false },
    { name: 'Research', href: '/research', accent: false },
    { name: 'Publications', href: '/publications', accent: false },
    { name: 'People', href: '/mentorship', accent: false },
    { name: 'Teaching', href: '/teaching', accent: false },
    { name: 'News', href: '/news', accent: false },
    { name: 'Outreach', href: '/outreach', accent: false },
    { name: 'Field Work', href: '/field-work', accent: false },
    { name: 'Opportunities', href: '/opportunities', accent: true },
  ],
  about_gallery: [],
  affiliations: [
    { name: 'American Scientific Affiliation' },
    { name: 'Society for Conservation Biology (Global & Nigeria)' },
    { name: 'British Ecological Society' },
    { name: 'Stable Planet Alliance' },
  ],
  research_themes: [
    { icon: 'trees', title: 'Urban Ecology', description: 'Investigating how rapid urbanization shapes bird communities and alters the ecological processes that sustain biodiversity in cities.', image: '' },
    { icon: 'mic', title: 'Bioacoustics', description: 'Using sound as a non-invasive lens to monitor biodiversity, revealing hidden ecological patterns in urban environments.', image: '' },
    { icon: 'leaf', title: 'Plant-Animal Interactions', description: 'Studying the mutualistic relationships between plants and animals — particularly frugivory and seed dispersal — and how land-use change disrupts these critical ecological networks.', image: '' },
    { icon: 'globe', title: 'Human-Nature Dynamics', description: 'Exploring the relationship between people and nature, emphasizing community engagement for sustainable cities.', image: '' },
  ],
  research_projects: [
    {
      theme: 'Bioacoustics',
      status: 'Current Project',
      title: 'Urban Campus Soundscape Project',
      location: 'Cornell University, Ithaca NY',
      description: 'Using autonomous acoustic recorders deployed across university campuses and cities in multiple countries, this project investigates bird diversity in rapidly changing urban landscapes. I collaborate with local experts and students to record bird songs—identifying which species persist, which do not, and why—to understand the factors that shape urban bird populations and guide conservation planning.',
      methods: 'Autonomous acoustic recorders, Community science, Bioacoustics analysis',
      network: JSON.stringify({
        network_name: 'Campus Biodiversity Network',
        stats: { institutions: 23, countries: 12, expanding: true },
        previous_countries: ['Brazil', 'Canada', 'France', 'Kenya', 'Senegal'],
        current_countries: ['Brazil', 'Canada', 'France', 'Kenya', 'Senegal', 'Nigeria', 'South Africa', 'India', 'Colombia', 'Spain', 'Belgium', 'United States'],
        network_url: 'https://www.biodivcampus.org/en/institutions',
      }),
    },
    {
      theme: 'Urban Ecology',
      status: 'Past Project',
      title: 'Multi-country Urban Bird Monitoring',
      location: "Queen's University, Canada",
      description: 'As a Postdoctoral Research Fellow at Queen\'s University, I coordinated a global urban bird survey project spanning five countries — Brazil, Canada, France, Kenya, and Senegal. The project used passive acoustic recorders and an innovative Community Science approach, actively involving local experts and the public in data collection. The aim was to promote human–wildlife coexistence while addressing geographic and methodological gaps in urban ecology research.',
      methods: 'Passive acoustic recorders, Community science, Comparative ecology',
    },
    {
      theme: 'Plant-Animal Interactions',
      status: 'Doctoral Research',
      title: 'Frugivory & Seed Dispersal in Urban Mosaics',
      location: 'University of KwaZulu-Natal, South Africa',
      description: 'My doctoral research focused on frugivory and seed dispersal by birds, bats, and monkeys in urban mosaic landscapes, with particular attention to the ecological role of Ficus species. The work demonstrated how habitat fragmentation disrupts mutualistic plant–animal interactions, with significant implications for forest regeneration in heavily modified environments.',
      methods: 'Field surveys, Plant-animal interaction networks, Frugivory analysis',
    },
  ],
  field_work_entries: [
    {
      region: 'Southern Africa — KwaZulu-Natal',
      caption: 'Doctoral fieldwork on frugivory and seed dispersal by birds, bats and vervet monkeys in urban-mosaic landscapes around Durban, South Africa, with a focus on the ecological role of native Ficus species.',
      photos: [
        {
          image: '/images/field-fruit.png',
          caption: 'Documenting frugivore visits to a fruiting Ficus tree during dawn focal-tree watches in KwaZulu-Natal, South Africa.',
        },
        {
          image: '/images/forest-bg.png',
          caption: 'Forest edge habitat at one of the long-term focal-tree observation sites in the urban-rural mosaic around Durban.',
        },
      ],
    },
    {
      region: 'West Africa — Nigeria',
      caption: 'Field training, community bird walks, and ongoing collaborations with the A.P. Leventis Ornithological Research Institute and partner institutions across Nigeria.',
      photos: [
        {
          image: '/images/teaching-field-outing.jpg',
          caption: 'Leading a hands-on field ornithology training session at the A.P. Leventis Ornithological Research Institute, Amurum Forest Reserve, Nigeria.',
        },
        {
          image: '/images/hero-bird.png',
          caption: 'Resident bird species photographed during a community bird walk with students and local birders in northern Nigeria.',
        },
      ],
    },
    {
      region: 'North America — Cornell & the Northeast',
      caption: 'Active deployment of autonomous acoustic recorders across the Cornell University campus and surrounding urban areas, monitoring bird community composition and dawn-chorus soundscapes through the seasons.',
      photos: [
        {
          image: '/images/spectrogram-art.png',
          caption: 'Spectrogram of dawn-chorus recordings captured by autonomous acoustic recorders deployed across a Cornell campus transect.',
        },
        {
          image: '/images/teaching-conference.jpg',
          caption: 'Working session with collaborators and students on community-science protocols for the Campus Biodiversity Network.',
        },
      ],
    },
  ],
  field_work_projects: [
    {
      status: 'Doctoral Fieldwork',
      title: 'Frugivore & Fig Tree Surveys — KwaZulu-Natal',
      location: 'Durban, South Africa',
      description: 'Intensive focal-tree observations and transect surveys across urban mosaic landscapes in the Durban metro area, documenting frugivore visits to native Ficus species by birds, bats, and vervet monkeys. Data collection involved dawn-to-dusk watches at fruiting trees to characterise visitation rates, species richness, and seed dispersal quality across a gradient of habitat fragmentation.',
      methods: 'Focal-tree watches, Transect surveys, Video recording, Seed viability testing',
    },
    {
      status: 'Past Fieldwork',
      title: 'Acoustic Recorder Deployment — Global Urban Transects',
      location: 'Brazil · Canada · France · Kenya · Senegal',
      description: 'Coordinated the deployment and retrieval of passive acoustic recorders along standardised urban transects in five countries as part of the multi-country urban bird monitoring initiative at Queen\'s University. Worked closely with in-country collaborators and community scientists to select sites, install equipment, and train local volunteers in recorder maintenance and field protocols.',
      methods: 'Passive acoustic recorders, Site selection surveys, Community science protocols',
    },
    {
      status: 'Active Fieldwork',
      title: 'Campus Bird Soundscape Monitoring — Cornell',
      location: 'Ithaca, NY, USA',
      description: 'On-the-ground deployment of autonomous acoustic recording units (ARUs) across the Cornell University campus and surrounding urban areas. Fieldwork involves seasonal installation and retrieval of recorders, GPS mapping of recording stations, and quality checks of captured audio files for downstream bioacoustic analysis of bird community composition and diel soundscape patterns.',
      methods: 'ARU deployment, GPS mapping, Audio quality control, Seasonal monitoring',
    },
  ],
  publications: [
    { title: 'Does Ficus species fruit mastication and ingestion by Wahlberg\'s epauletted fruit bats enhance seed germination and seedling emergence?', authors: 'Raji, I.A. & Downs, C.T.', journal: 'African Journal of Ecology', year: '2024', category: 'Journal Article', url: 'https://onlinelibrary.wiley.com/doi/10.1111/aje.13250' },
    { title: 'Farmers and pastoralists\' socio-cultural interaction: mitigating conflicts in rural communities for livelihood development in Nigeria', authors: 'Aderinoye-Abdulwahab, S.A., Adebayo, J.A., Raza, H.A., Dolapo, T.A. & Raji, I.A.', journal: 'Journal of Global Innovations in Agricultural Sciences', year: '2023', category: 'Journal Article', url: 'https://scholar.google.com/citations?user=LqhoC-4AAAAJ&hl=en' },
    { title: 'Fruiting phenology and diversity of native Ficus species in an urban-forest mosaic landscape in KwaZulu-Natal, South Africa', authors: 'Raji, I.A. & Downs, C.T.', journal: 'African Journal of Ecology', year: '2022', category: 'Journal Article', url: 'https://onlinelibrary.wiley.com/doi/10.1111/aje.13017' },
    { title: 'Tree visitation and potential seed dispersal of keystone Ficus species by vertebrates in an urban mosaic landscape in eastern South Africa', authors: 'Raji, I.A. & Downs, C.T.', journal: 'Acta Oecologica', year: '2022', category: 'Journal Article', url: 'https://www.sciencedirect.com/science/article/abs/pii/S1146609X22000558' },
    { title: 'Seed dispersal by frugivores and germination of the invasive alien shrub Pyracantha angustifolia (Franch.) C.K. Schneid. in Free State Province, South Africa', authors: 'Adams, L.D., Martin, G.D., Downs, C.T., Clark, V.R., Thabethe, V. & Raji, I.A.', journal: 'Biological Invasions', year: '2022', category: 'Journal Article', url: 'https://link.springer.com/article/10.1007/s10530-022-02807-5' },
    { title: 'The role of avian frugivores in the germination and dispersal of fleshy-fruited Ficus species in KwaZulu-Natal, South Africa', authors: 'Raji, I.A., Thabethe, V. & Downs, C.T.', journal: 'Journal of Ornithology', year: '2022', category: 'Journal Article', url: 'https://link.springer.com/article/10.1007/s10336-022-01963-8' },
    { title: 'Ficus-frugivore interactions, especially in areas of land-use change, in Africa: A systematic review', authors: 'Raji, I.A. & Downs, C.T.', journal: 'Acta Oecologica', year: '2021', category: 'Journal Article', url: 'https://www.sciencedirect.com/science/article/abs/pii/S1146609X21000734' },
    { title: 'Bird species use of Tapinanthus dodoneifolius mistletoes parasitising African locust bean trees Parkia biglobosa in Amurum Forest Reserve, Nigeria', authors: 'Raji, I.A., Manu, S., Chaskda, A. & Pomeroy, D.', journal: 'Journal of Ornithology', year: '2021', category: 'Journal Article', url: 'https://link.springer.com/article/10.1007/s10336-021-01890-0' },
    { title: 'Modification of the third phase in the framework for vertebrate species persistence in urban mosaic environments', authors: 'Downs, C.T., Alexander, J., Brown, M., Chibesa, M., Ehlers Smith, Y.C. & Raji, I.A. et al.', journal: 'Ambio', year: '2021', category: 'Journal Article', url: 'https://link.springer.com/article/10.1007/s13280-021-01501-5' },
    { title: 'Effects of land-use changes on the distribution and use of Ficus species by frugivores in the urban mosaic landscape of Durban, KwaZulu-Natal, South Africa', authors: 'Raji, I.A.', journal: 'PhD Thesis, University of KwaZulu-Natal', year: '2021', category: 'Thesis Chapter', url: 'https://scholar.google.com/citations?user=LqhoC-4AAAAJ&hl=en' },
    { title: 'Assessment of tree diversity and abundance in University of Ilorin campus: Towards conservation', authors: 'Raji, I.A. & Babalola, F.D.', journal: 'Proceedings of the 6th NSCB Biodiversity Conference', year: '2018', category: 'Conference Paper', url: 'https://scholar.google.com/citations?user=LqhoC-4AAAAJ&hl=en' },
    { title: 'Ecosystem services provided by mangroves and contributions to sustainable livelihoods', authors: 'Babalola, F.D., Opii, E.E., Raji, I.A., Amusa, T.O. & Sadiku, N.A.', journal: 'Mangroves and Wetlands of Sub-Saharan Africa', year: '2016', category: 'Book Chapter', url: 'https://scholar.google.com/citations?user=LqhoC-4AAAAJ&hl=en' },
    { title: 'Perception of urban trees at main campus of University of Ilorin, Ilorin, Kwara State, Nigeria', authors: 'Raji, I.A. & Babalola, F.D.', journal: 'Applied Tropical Agriculture', year: '2016', category: 'Journal Article', url: 'https://scholar.google.com/citations?user=LqhoC-4AAAAJ&hl=en' },
  ],
  news_items: [
    {
      date: '2025',
      title: 'Joined Cornell Lab as Rose Postdoctoral Fellow',
      description: 'Excited to begin my fellowship at the K. Lisa Yang Center for Conservation Bioacoustics, Cornell Lab of Ornithology, advancing interdisciplinary research on urban bird diversity and soundscapes.',
    },
    {
      date: '2024',
      title: 'Multi-country urban bird monitoring project complete',
      description: 'Wrapped up the global urban bird survey project across five countries — Brazil, Canada, France, Kenya, and Senegal — at Queen\'s University, with data analysis and manuscript preparation now underway.',
    },
    {
      date: '2024',
      title: 'Fieldwork season completed in South Africa',
      description: 'Concluded field data collection on frugivory and seed dispersal networks by birds, bats, and monkeys in urban mosaic landscapes, focusing on the ecological role of Ficus species.',
    },
    {
      date: '2021',
      title: 'PhD conferred — University of KwaZulu-Natal',
      description: 'Completed doctoral research in Ecological Sciences, focusing on plant–animal interactions and seed dispersal in fragmented urban landscapes in South Africa.',
    },
  ],
  mentorship_roles: [
    {
      title: 'Collaborators',
      description: 'Always open to interdisciplinary collaborations crossing ecology, urban planning, and community science.',
    },
    {
      title: 'Prospective Graduate Students',
      description: 'Please reach out if you are interested in urban bioacoustics or plant-animal interactions. I welcome MSc and PhD applicants with a passion for field ecology.',
    },
  ],
  opportunities_list: [],
  teaching_courses: [
    {
      status: 'Current',
      title: 'Urban Ecology and Biodiversity',
      code: 'NTRES 4850',
      institution: 'Cornell University',
      semester: 'Spring 2025',
      role: 'Instructor of Record',
      description: 'An advanced undergraduate course exploring how urbanisation shapes ecological communities, with a focus on birds, plants, and ecosystem services. Students conduct field surveys using bioacoustic methods and participate in community science projects.',
      syllabus_url: '',
    },
    {
      status: 'Past',
      title: 'Conservation Biology',
      code: 'BIOL 3200',
      institution: "Queen's University, Canada",
      semester: 'Fall 2023',
      role: 'Guest Lecturer',
      description: 'Delivered lectures on urban wildlife conservation, bioacoustics as a monitoring tool, and community-based approaches to biodiversity assessment in rapidly changing landscapes.',
      syllabus_url: '',
    },
    {
      status: 'Past',
      title: 'Field Ornithology Training Workshop',
      code: '',
      institution: 'A.P. Leventis Ornithological Research Institute, Nigeria',
      semester: '2023',
      role: 'Workshop Instructor',
      description: 'Hands-on field ornithology training for early-career researchers and students covering bird identification, binocular use, mist-netting techniques, and field survey design in forest reserve habitats.',
      syllabus_url: '',
    },
  ],
  collaborators: [
    { image: '', name: 'Collaborator Name', role: 'Associate Professor', institution: 'University Name', description: 'Brief description of collaboration and shared research interests.', email: '', links: '' },
  ],
  mentees: [
    { image: '', name: 'Mentee Name', role: 'PhD Student', institution: 'University Name', description: 'Research focus and mentoring context.', email: '', links: '' },
  ],
  funding: [
    { image: '', name: 'Funding Body', role: 'Grant / Award Title', institution: '', description: 'Brief description of the funded project or award.', email: '', links: '' },
  ],
  outreach_engagement: [
    {
      title: 'Falling Walls Female Science Talent — Public Lecture',
      date: '2024',
      venue: 'Berlin, Germany',
      description: 'Selected as a Falling Walls Female Science Talent and delivered a public lecture on how bioacoustics and community science can transform biodiversity monitoring in cities across the Global South.',
      url: 'https://falling-walls.com/people/islamiat-raji-adebayo/',
    },
    {
      title: 'Campus Biodiversity Network — Community Science Launch',
      date: '2023–present',
      venue: 'Brazil · Canada · France · Kenya · Senegal · Nigeria · South Africa · USA',
      description: 'Co-led the launch and ongoing coordination of a global Campus Biodiversity Network that engages students, faculty and local birders in deploying acoustic recorders and identifying urban bird species. The initiative now spans more than 20 institutions across 12 countries.',
      url: 'https://www.biodivcampus.org/en/institutions',
    },
    {
      title: 'IMPACT Fellow — National Postdoctoral Association',
      date: '2024',
      venue: 'Virtual / United States',
      description: 'Engaged in a year-long fellowship focused on broadening participation in science, mentoring early-career researchers from underrepresented backgrounds, and co-developing outreach activities that connect ecology to public well-being.',
      url: 'https://www.nationalpostdoc.org/page/IMPACT',
    },
    {
      title: 'Field Ornithology Training Workshop',
      date: '2023',
      venue: 'A.P. Leventis Ornithological Research Institute, Nigeria',
      description: 'Designed and led a hands-on training workshop for early-career Nigerian researchers and students on bird identification, mist-netting, point counts and acoustic monitoring in Amurum Forest Reserve.',
      url: '',
    },
    {
      title: 'School & Community Bird Walks',
      date: 'Ongoing',
      venue: 'Ithaca, NY · Durban, South Africa · Ilorin, Nigeria',
      description: 'Lead birding walks and listening sessions for school groups and local community members, introducing participants to common urban birds, soundscape ecology, and how everyday observations can contribute to conservation science.',
      url: '',
    },
    {
      title: 'Frugivores & Seed Dispersal Conference — Invited Talk',
      date: '2020',
      venue: 'Corbett, India',
      description: 'Presented research on Ficus–frugivore interactions and the role of birds, bats and primates in maintaining urban forest regeneration to an international audience of ecologists and conservation practitioners.',
      url: '',
    },
  ],
  science_writing: [
    {
      title: 'Listening to cities: how bioacoustics is reshaping urban biodiversity monitoring',
      publication: 'Cornell Lab of Ornithology — All About Birds',
      date: '2025',
      description: 'A piece introducing general readers to the ways autonomous recording units and machine learning are letting researchers eavesdrop on urban bird communities at scale, and what those soundscapes reveal about the health of our cities.',
      url: 'https://www.allaboutbirds.org/news/',
    },
    {
      title: 'Why community science is essential for urban conservation in the Global South',
      publication: 'The Conversation Africa',
      date: '2024',
      description: 'An op-ed arguing that locally led, community-driven monitoring programs are critical for filling biodiversity data gaps in African and Latin American cities, drawing on lessons from a five-country urban bird survey.',
      url: 'https://theconversation.com/africa',
    },
    {
      title: 'Fig trees, fruit bats and the hidden architecture of African cities',
      publication: 'Mongabay',
      date: '2023',
      description: 'A long-form feature on how native Ficus species act as keystone resources for birds, bats and monkeys in fragmented urban landscapes, and what their loss would mean for forest regeneration in sub-Saharan Africa.',
      url: 'https://news.mongabay.com/',
    },
    {
      title: 'Birds as barometers: what urban soundscapes tell us about climate and land-use change',
      publication: 'British Ecological Society — Niche Magazine',
      date: '2023',
      description: 'A short essay for BES members on using passive acoustic monitoring as an early-warning system for shifts in urban bird communities driven by warming, noise pollution and habitat loss.',
      url: 'https://www.britishecologicalsociety.org/membership-community/niche/',
    },
    {
      title: 'From Ilorin to Ithaca: a Nigerian ecologist’s journey through urban bird research',
      publication: 'Nature Careers',
      date: '2024',
      description: 'A first-person career feature reflecting on training across Nigeria, South Africa, Canada and the United States, and on building inclusive international research collaborations in conservation bioacoustics.',
      url: 'https://www.nature.com/nature-careers',
    },
    {
      title: 'How to start a campus bird monitoring program (a practical guide)',
      publication: 'Campus Biodiversity Network Blog',
      date: '2024',
      description: 'A step-by-step practitioner guide for students and faculty interested in deploying acoustic recorders on their campuses, including site selection, ethics, data sharing and how to engage local communities.',
      url: 'https://www.biodivcampus.org/en/',
    },
  ],
  teaching_events: [
    {
      image: '/images/teaching-field-outing.jpg',
      title: 'Field Ornithology Training — Amurum Forest Reserve',
      date: '2023',
      location: 'Nigeria',
      description: 'Led a hands-on field ornithology workshop training early-career researchers and students in bird identification, binocular use, and field survey techniques in the forest reserve.',
    },
    {
      image: '/images/teaching-conference.jpg',
      title: 'Frugivores & Seed Dispersal Conference 2020',
      date: '2020',
      location: 'Corbett, India',
      description: 'Presented research on Ficus-frugivore interactions and seed dispersal networks at the international Frugivores & Seed Dispersal Conference, sharing findings with global ecology and conservation audiences.',
    },
  ],
  resources: [
    {
      audience: 'Undergraduate',
      category: 'Internship',
      title: 'NSF Research Experiences for Undergraduates (REU)',
      organization: 'U.S. National Science Foundation',
      description: 'Paid summer research internships at host institutions across the United States in ecology, biology, and environmental sciences.',
      deadline: 'Varies (typically Jan–Feb)',
      url: 'https://www.nsf.gov/funding/initiatives/reu',
    },
    {
      audience: 'Undergraduate',
      category: 'Scholarship',
      title: 'Fuertes Award for Field Ornithology',
      organization: 'Wilson Ornithological Society',
      description: 'Small grant supporting undergraduate and early-career field ornithology projects.',
      deadline: 'February (annual)',
      url: 'https://wilsonsociety.org/awards/',
    },
    {
      audience: 'Graduate',
      category: 'Fellowship',
      title: 'NSF Graduate Research Fellowship Program (GRFP)',
      organization: 'U.S. National Science Foundation',
      description: 'Three years of stipend and tuition support for U.S.-based graduate students pursuing research-based MSc and PhD degrees in STEM, including ecology and bioacoustics.',
      deadline: 'October (annual)',
      url: 'https://www.nsfgrfp.org/',
    },
    {
      audience: 'Graduate',
      category: 'Research Grant',
      title: 'American Ornithological Society Research Awards',
      organization: 'American Ornithological Society',
      description: 'Competitive research grants for graduate students conducting field-based ornithological research, including bioacoustic monitoring projects.',
      deadline: 'February (annual)',
      url: 'https://americanornithology.org/about/awards-and-grants/',
    },
    {
      audience: 'Graduate',
      category: 'Scholarship',
      title: 'Schlumberger Foundation Faculty for the Future',
      organization: 'Schlumberger Foundation',
      description: 'Fellowships for women from developing and emerging economies pursuing PhD or postdoctoral research in STEM at top universities abroad.',
      deadline: 'November (annual)',
      url: 'https://www.facultyforthefuture.net/',
    },
    {
      audience: 'Postgraduate',
      category: 'Fellowship',
      title: 'Rose Postdoctoral Fellowship',
      organization: 'Cornell Lab of Ornithology',
      description: 'Two-year postdoctoral fellowship supporting independent research in ornithology, conservation science, and related fields at the Cornell Lab.',
      deadline: 'October (annual)',
      url: 'https://www.birds.cornell.edu/home/rose-postdoctoral-fellowship/',
    },
    {
      audience: 'Postgraduate',
      category: 'Fellowship',
      title: 'L\'Oréal-UNESCO For Women in Science',
      organization: 'L\'Oréal Foundation & UNESCO',
      description: 'Regional and international fellowships recognising and supporting outstanding women postdoctoral researchers in the natural sciences.',
      deadline: 'Varies by region',
      url: 'https://www.forwomeninscience.com/',
    },
    {
      audience: 'Postgraduate',
      category: 'Research Grant',
      title: 'National Geographic Society Explorer Grants',
      organization: 'National Geographic Society',
      description: 'Funding for early-career and established researchers leading conservation, exploration, and storytelling projects worldwide.',
      deadline: 'Rolling (multiple cycles per year)',
      url: 'https://www.nationalgeographic.org/funding-opportunities/grants/',
    },
    {
      audience: 'Collaborators',
      category: 'Recruitment',
      title: 'Join the Campus Biodiversity Network',
      organization: 'Campus Biodiversity Network',
      description: 'Open call for university partners interested in deploying autonomous acoustic recorders on their campuses to contribute to a global urban bird monitoring dataset.',
      deadline: 'Rolling',
      url: 'https://www.biodivcampus.org/en/',
    },
    {
      audience: 'Collaborators',
      category: 'Research Grant',
      title: 'Cornell Atkinson Center Rapid Response Fund',
      organization: 'Cornell Atkinson Center for Sustainability',
      description: 'Seed funding for collaborative, interdisciplinary projects addressing urgent sustainability and conservation challenges, open to Cornell-affiliated collaborators.',
      deadline: 'Rolling',
      url: 'https://atkinson.cornell.edu/funding-opportunities/',
    },
  ],
};
